interface EndpointDefinition {
  method: HttpMethod;
  route: string;
  description: string;
}

type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

type RouteParameters = Record<string, string | number | boolean>;

const ENDPOINT_CATALOG = Object.freeze([
  { method: "GET", route: "/api/auth/state", description: "Get authentication state and CSRF token" },
  { method: "POST", route: "/api/auth/login", description: "Login with password" },
  { method: "POST", route: "/api/auth/logout", description: "Logout current session" },
  { method: "GET", route: "/api/health", description: "Health check" },
  { method: "GET", route: "/api/setup/state", description: "Get setup completion state" },
  { method: "POST", route: "/api/setup/preflight", description: "Run preflight checks" },
  { method: "POST", route: "/api/setup/write-config", description: "Write setup config" },
  { method: "POST", route: "/api/setup/save-token", description: "Save Funcom token" },
  { method: "POST", route: "/api/setup/init", description: "Initialize setup" },
  { method: "GET", route: "/api/setup/tasks", description: "List background tasks" },
  { method: "GET", route: "/api/setup/tasks/{id}", description: "Get task status" },
  { method: "GET", route: "/api/setup/tasks/{id}/stream", description: "Stream task output (SSE)" },
  { method: "GET", route: "/api/server/status", description: "Server status command" },
  { method: "GET", route: "/api/server/performance", description: "Performance snapshot (CPU, memory, disk)" },
  { method: "GET", route: "/api/server/readiness", description: "Service readiness check" },
  { method: "GET", route: "/api/server/ports", description: "List service ports" },
  { method: "GET", route: "/api/server/services", description: "List services and status" },
  { method: "GET", route: "/api/server/doctor", description: "Run diagnostic check" },
  { method: "POST", route: "/api/server/network-bind/fix", description: "Fix network binding issue" },
  { method: "POST", route: "/api/server/storage/cleanup-images", description: "Clean obsolete Docker images" },
  { method: "POST", route: "/api/server/storage/cleanup-build-cache", description: "Clean Docker build cache" },
  { method: "POST", route: "/api/server/start", description: "Start server" },
  { method: "POST", route: "/api/server/stop", description: "Stop server" },
  { method: "POST", route: "/api/server/restart", description: "Restart all services" },
  { method: "POST", route: "/api/server/restart-service", description: "Restart specific service" },
  { method: "POST", route: "/api/server/title", description: "Set server title" },
  { method: "POST", route: "/api/server/config", description: "Set server config" },
  { method: "POST", route: "/api/server/funcom-token", description: "Save Funcom token" },
  { method: "GET", route: "/api/server/funcom-token/check", description: "Check Funcom token validity" },
  { method: "GET", route: "/api/server/restart-schedule", description: "Get restart schedule status" },
  { method: "POST", route: "/api/server/restart-schedule", description: "Save restart schedule" },
  { method: "GET", route: "/api/server/ip-change-restart", description: "Get IP change restart status" },
  { method: "POST", route: "/api/server/ip-change-restart", description: "Save IP change restart config" },
  { method: "POST", route: "/api/server/ip-change-restart/check", description: "Check for IP changes now" },
  { method: "GET", route: "/api/server/restart-queue", description: "Get restart-queue settings, defaults, active state and battlegroup online count" },
  { method: "POST", route: "/api/server/restart-queue", description: "Save restart-queue settings (partial; merges onto the current settings)" },
  { method: "POST", route: "/api/server/restart-queue/cancel", description: "Cancel one active countdown" },
  { method: "POST", route: "/api/server/restart-queue/restart-now", description: "Execute one queued restart immediately" },
  { method: "GET", route: "/api/server/shutdown-protection", description: "Get shutdown protection status" },
  { method: "POST", route: "/api/server/shutdown-protection", description: "Enable/disable shutdown protection" },
  { method: "POST", route: "/api/server/shutdown-protection/remove", description: "Remove shutdown protection" },
  { method: "POST", route: "/api/updates/check-game", description: "Check for game updates" },
  { method: "POST", route: "/api/updates/apply-game", description: "Apply game updates" },
  { method: "POST", route: "/api/updates/fix-steamcmd", description: "Fix SteamCMD issues" },
  { method: "POST", route: "/api/updates/check-stack", description: "Check for stack updates" },
  { method: "POST", route: "/api/updates/apply-stack", description: "Apply stack updates" },
  { method: "GET", route: "/api/updates/auto-game", description: "Get auto-update status" },
  { method: "POST", route: "/api/updates/auto-game", description: "Save auto-update config" },
  { method: "POST", route: "/api/updates/repair-runtime", description: "Repair runtime installation" },
  { method: "GET", route: "/api/backups", description: "List all backups" },
  { method: "POST", route: "/api/backups/create", description: "Create new backup" },
  { method: "POST", route: "/api/backups/restore", description: "Restore from backup" },
  { method: "GET", route: "/api/backups/{backup}/download", description: "Download backup archive" },
  { method: "DELETE", route: "/api/backups/{backup}", description: "Delete backup" },
  { method: "POST", route: "/api/backups/delete-all", description: "Delete all backups" },
  { method: "POST", route: "/api/backups/import-external", description: "Import external backup" },
  { method: "GET", route: "/api/backups/auto", description: "Get auto-backup status" },
  { method: "POST", route: "/api/backups/auto", description: "Save auto-backup config" },
  { method: "GET", route: "/api/players", description: "List players (paginated)" },
  { method: "GET", route: "/api/players/online", description: "List currently online players" },
  { method: "GET", route: "/api/players/search", description: "Search players by name/ID" },
  { method: "GET", route: "/api/players/{playerId}", description: "Get player profile summary" },
  { method: "GET", route: "/api/players/{playerId}/inventory", description: "Get player inventory items — backpack, character gear, loadout, and unique-gear schematics (emote containers excluded), each row tagged with `inventory_type`" },
  { method: "GET", route: "/api/players/{playerId}/vehicles", description: "Get vehicles owned by or shared with the player, including the player's access relationship" },
  { method: "GET", route: "/api/players/{playerId}/currency", description: "Get player currency totals" },
  { method: "GET", route: "/api/players/{playerId}/solaris-coin", description: "Get Solaris Coin total" },
  { method: "GET", route: "/api/players/{playerId}/factions", description: "Get faction reputation" },
  { method: "GET", route: "/api/players/{playerId}/intel", description: "Get intel data" },
  { method: "GET", route: "/api/players/{playerId}/specs", description: "Get skill specializations" },
  { method: "GET", route: "/api/players/{playerId}/position", description: "Get player position on map" },
  { method: "GET", route: "/api/players/{playerId}/progression", description: "Get level and progression" },
  { method: "GET", route: "/api/players/{playerId}/vitals", description: "Get health/hydration/addiction" },
  { method: "GET", route: "/api/players/{playerId}/crafting-recipes", description: "Get unlocked recipes" },
  { method: "GET", route: "/api/players/{playerId}/research-items", description: "Get research progress" },
  { method: "GET", route: "/api/players/{playerId}/journey", description: "Get journey node completion" },
  { method: "GET", route: "/api/players/{playerId}/events", description: "Get player events" },
  { method: "GET", route: "/api/players/{playerId}/stats", description: "Get player stats" },
  { method: "GET", route: "/api/players/{playerId}/history", description: "Get player history" },
  { method: "POST", route: "/api/players/{playerId}/give-item", description: "Give item by name" },
  { method: "POST", route: "/api/players/{playerId}/give-items", description: "Give multiple items" },
  { method: "POST", route: "/api/players/{playerId}/give-item-id", description: "Give item by template ID" },
  { method: "POST", route: "/api/players/{playerId}/add-xp", description: "Add XP" },
  { method: "POST", route: "/api/players/{playerId}/set-skill-points", description: "Set skill points" },
  { method: "POST", route: "/api/players/{playerId}/set-skill-module", description: "Set skill module" },
  { method: "POST", route: "/api/players/{playerId}/refill-water", description: "Refill hydration" },
  { method: "POST", route: "/api/players/{playerId}/kick", description: "Kick player from server" },
  { method: "GET", route: "/api/players/{playerId}/ban", description: "Get persistent account-ban status" },
  { method: "POST", route: "/api/players/{playerId}/ban", description: "Persistently ban and enforce removal of a player's FLS account" },
  { method: "DELETE", route: "/api/players/{playerId}/ban", description: "Remove a persistent account ban" },
  { method: "POST", route: "/api/players/{playerId}/repair-login-queue", description: "Fix login queue issues" },
  { method: "POST", route: "/api/players/{playerId}/teleport", description: "Teleport to coordinates" },
  { method: "POST", route: "/api/players/{playerId}/spawn-vehicle", description: "Spawn vehicle" },
  { method: "POST", route: "/api/players/{playerId}/clean-inventory", description: "Remove invalid items" },
  { method: "POST", route: "/api/players/{playerId}/reset-progression", description: "Reset character level" },
  { method: "POST", route: "/api/players/{playerId}/add-currency", description: "Add currency" },
  { method: "POST", route: "/api/players/{playerId}/add-faction-reputation", description: "Add faction reputation" },
  { method: "POST", route: "/api/players/{playerId}/faction", description: "Assign Atreides, Harkonnen, or Neutral" },
  { method: "POST", route: "/api/players/{playerId}/add-intel", description: "Add intel" },
  { method: "POST", route: "/api/players/{playerId}/specializations/add-xp", description: "Add spec XP" },
  { method: "POST", route: "/api/players/{playerId}/specializations/grant-max", description: "Max out specialization" },
  { method: "POST", route: "/api/players/{playerId}/specializations/reset", description: "Reset specialization" },
  { method: "POST", route: "/api/players/{playerId}/specializations/keystones/grant-all", description: "Grant all keystones" },
  { method: "POST", route: "/api/players/{playerId}/specializations/keystones/reset-all", description: "Reset all keystones" },
  { method: "POST", route: "/api/players/{playerId}/crafting-recipes/unlock", description: "Unlock recipe" },
  { method: "POST", route: "/api/players/{playerId}/research-items/unlock", description: "Unlock research" },
  { method: "POST", route: "/api/players/{playerId}/journey/complete", description: "Complete journey node" },
  { method: "POST", route: "/api/players/{playerId}/journey/reset", description: "Reset journey node" },
  { method: "POST", route: "/api/players/{playerId}/tutorials/complete", description: "Complete tutorial" },
  { method: "POST", route: "/api/players/{playerId}/tutorials/reset", description: "Reset tutorial" },
  { method: "POST", route: "/api/players/{playerId}/repair-gear", description: "Repair all equipment" },
  { method: "POST", route: "/api/players/{playerId}/repair-vehicle-decay", description: "Repair vehicle decay" },
  { method: "POST", route: "/api/players/{playerId}/refuel-vehicle", description: "Refuel vehicle" },
  { method: "POST", route: "/api/players/{playerId}/augment-item", description: "Apply augments to item" },
  { method: "DELETE", route: "/api/players/{playerId}/inventory/{itemId}", description: "Delete inventory item" },
  { method: "PATCH", route: "/api/players/{playerId}/inventory/{itemId}", description: "Modify inventory item" },
  { method: "POST", route: "/api/players/kick-all-online", description: "Kick all online players" },
  { method: "GET", route: "/api/guilds", description: "List guilds (paginated)" },
  { method: "GET", route: "/api/guilds/{guildId}/members", description: "Get guild member list" },
  { method: "GET", route: "/api/bases", description: "List bases (paginated)" },
  { method: "GET", route: "/api/bases/{baseId}/export", description: "Export base as blueprint" },
  { method: "POST", route: "/api/bases/{baseId}/refill-generators", description: "Refill all base generators (queued instead if the map isn't safely writable right now)" },
  { method: "GET", route: "/api/bases/pending-refills", description: "List queued generator refills, grouped by restart target" },
  { method: "DELETE", route: "/api/bases/{baseId}/queued-refill", description: "Cancel a base's queued generator refill" },
  { method: "GET", route: "/api/bases/auto-refill", description: "Get per-base auto-refill enrollment state" },
  { method: "POST", route: "/api/bases/{baseId}/auto-refill", description: "Enable/disable auto-refill for a base" },
  { method: "GET", route: "/api/bases/auto-refill/settings", description: "Get the threshold and scan interval for both auto-refill subsystems, with the source (`console`/`env`/`default`), reset value, and range of each" },
  { method: "POST", route: "/api/bases/auto-refill/settings", description: "Save auto-refill thresholds/intervals. A number sets, `null` resets to the env/default layer, an omitted key is unchanged. Rate limited; requires `bases:write-config`, not `bases:mutate`" },
  { method: "GET", route: "/api/bases/{baseId}/water", description: "Get a base's water storage containers (count, volume, fill %; blood volume/fill for Blood Purifiers)" },
  { method: "POST", route: "/api/bases/{baseId}/refill-water", description: "Refill all base water storage (queued instead if the map isn't safely writable right now). Water only -- blood is never touched" },
  { method: "GET", route: "/api/bases/pending-water-refills", description: "List queued water refills, grouped by restart target" },
  { method: "DELETE", route: "/api/bases/{baseId}/queued-water-refill", description: "Cancel a base's queued water refill" },
  { method: "GET", route: "/api/bases/auto-refill-water", description: "Get per-base water auto-refill enrollment state" },
  { method: "POST", route: "/api/bases/{baseId}/auto-refill-water", description: "Enable/disable water auto-refill for a base" },
  { method: "GET", route: "/api/bases/{baseId}/inventory", description: "Get a base's stored items, rolled up by item template and by container (storage, refining, crafting, other). Merged per template, not per slot" },
  { method: "GET", route: "/api/bases/{baseId}/containers/{placeableId}", description: "Get one container's inventories and their individual slots (item id, slot number, quantity, quality, durability, applied augments with their own per-augment quality), plus `deleteSafety` and `addSafety`. Answers `found: false` when that container is not at the base" },
  { method: "DELETE", route: "/api/bases/{baseId}/containers/{placeableId}/items/{itemId}", description: "Delete an item from a plain Storage container, or part of its stack with `count`. Refused unless the owning map is verifiably and safely stopped; Crafting and Refining contents are read-only. Requires `{ confirmation: \"DELETE ITEM\" }`" },
  { method: "POST", route: "/api/bases/{baseId}/containers/{placeableId}/items", description: "Add a new item to a plain Storage container. Always creates a new row at the next free slot — never merges into an existing stack, and the slot cannot be chosen. Refused unless the owning map is verifiably and safely stopped; Crafting and Refining contents are read-only. Requires `{ confirmation: \"ADD ITEM TO CONTAINER\" }`" },
  { method: "GET", route: "/api/bases/{baseId}/permissions", description: "Get a base's permission roster (Owner, Co-Owners, Associates)" },
  { method: "POST", route: "/api/bases/{baseId}/system-custodian", description: "Transfer ownership to the Server or detected GM system custodian while preserving the roster; provisions Server when no custodian exists" },
  { method: "PUT", route: "/api/bases/{baseId}/permissions", description: "Replace a base's permission roster" },
  { method: "GET", route: "/api/bases/permission-candidates", description: "Search players eligible to be added to a roster" },
  { method: "GET", route: "/api/bases/{baseId}/child-access", description: "Every child piece (door, device) on a base plus its own root totem (`is_child=false`), each with its access level — a different 5-tier scale from the roster rank above; Sub-Fief is Associate (3)" },
  { method: "POST", route: "/api/bases/{baseId}/child-access", description: "Set specific pieces to specific access levels (1-5); queued for the next map restart instead if the base's map is live (`result.queued`). Requires `{ updates: [{ actorId, accessLevel }], confirmation: \"SET CHILD ACCESS\" }`" },
  { method: "GET", route: "/api/bases/pending-child-access", description: "List queued permission changes, grouped by restart target. Each entry carries its own `updates[]` payload" },
  { method: "DELETE", route: "/api/bases/{baseId}/queued-child-access", description: "Discard a base's queued permission changes" },
  { method: "DELETE", route: "/api/bases/{baseId}", description: "Permanently delete a base and everything on it (queued instead if the map isn't safely writable right now); takes a full-database safety backup first. Requires `{ confirmation: \"DELETE BASE\" }`" },
  { method: "GET", route: "/api/bases/pending-deletes", description: "List queued base deletes, grouped by restart target" },
  { method: "DELETE", route: "/api/bases/{baseId}/queued-delete", description: "Cancel a base's queued delete" },
  { method: "GET", route: "/api/storage", description: "List all storage containers" },
  { method: "GET", route: "/api/storage/{storageId}", description: "Get storage details" },
  { method: "GET", route: "/api/storage/{storageId}/items", description: "Get storage inventory" },
  { method: "POST", route: "/api/storage/{storageId}/give-item", description: "Add item to storage" },
  { method: "GET", route: "/api/storage/{storageId}/export", description: "Export storage as JSON" },
  { method: "GET", route: "/api/vehicles", description: "List all player vehicles (paginated), each with owner, shared-with roster, lowest-component condition %, fuel %, map/partition, coordinates, and per-component durability" },
  { method: "GET", route: "/api/players/{playerId}/vehicles", description: "List the selected player's owned and shared vehicles using the same vehicle details" },
  { method: "GET", route: "/api/vehicles/{vehicleId}/permissions", description: "Get a vehicle's permission roster (Owner, Co-Owners, Associates) plus the detected system custodian" },
  { method: "PUT", route: "/api/vehicles/{vehicleId}/permissions", description: "Replace a vehicle's permission roster" },
  { method: "POST", route: "/api/vehicles/{vehicleId}/system-custodian", description: "Transfer ownership to the Server or detected GM system custodian while preserving the roster; provisions Server when no custodian exists" },
  { method: "GET", route: "/api/vehicles/permission-candidates", description: "Search players eligible to be added to a vehicle roster" },
  { method: "GET", route: "/api/vehicles/{vehicleId}/storage", description: "Read a vehicle's cargo hold slot by slot (read-only): capacity, per-slot item, quantity, grade, durability and augments" },
  { method: "DELETE", route: "/api/vehicles/{vehicleId}/storage/items/{itemId}", description: "Delete one stack from a vehicle's cargo hold, or part of it with `count`. Requires `{ confirmation: \"DELETE ITEM\" }`" },
  { method: "DELETE", route: "/api/vehicles/{vehicleId}/storage/items", description: "Delete a chosen set of whole stacks (max 200). Requires `{ confirmation: \"DELETE ITEMS\" }`" },
  { method: "DELETE", route: "/api/vehicles/{vehicleId}/storage/all-items", description: "Empty a vehicle's cargo hold. Requires `{ confirmation: \"DELETE ALL ITEMS\" }`" },
  { method: "DELETE", route: "/api/vehicles/{vehicleId}", description: "Permanently delete a vehicle and everything on it (queued instead if the map isn't safely writable right now); takes a full-database safety backup first. Requires `{ confirmation: \"DELETE VEHICLE\" }`" },
  { method: "GET", route: "/api/vehicles/pending-deletes", description: "List queued vehicle deletes, grouped by restart target" },
  { method: "DELETE", route: "/api/vehicles/{vehicleId}/queued-delete", description: "Cancel a vehicle's queued delete" },
  { method: "GET", route: "/api/exchange/items", description: "List active CHOAM exchange sell orders aggregated by item + grade (paginated): lowest price, total stock, listing count" },
  { method: "GET", route: "/api/exchange/listings", description: "List the individual sell orders for one item, each with a resolved seller" },
  { method: "GET", route: "/api/exchange/stats", description: "Aggregate totals (total, bot, player listings; unique items)" },
  { method: "GET", route: "/api/exchange/transactions", description: "Paginated completed-order activity captured from this Console release forward, plus filtered event/unit/value totals" },
  { method: "GET", route: "/api/exchange/config", description: "Read the console-local bot/blacklist filter config" },
  { method: "POST", route: "/api/exchange/config", description: "Save the bot/blacklist filter config (audited, rate-limited)" },
  { method: "GET", route: "/api/exchange/market", description: "Market Bot status: seed-plan availability, named seed-plan list (`plans`), both schedules, and the commodity-stack catalog" },
  { method: "GET", route: "/api/exchange/market/exchanges", description: "Discover exchanges (BIGINT ids as strings; access-pointed exchanges first)" },
  { method: "POST", route: "/api/exchange/market/buyback/probe", description: "Read-only buyback diagnostics: total, recognized, eligible, above-threshold, unknown-template, and invalid price/stack listing counts (no backup taken)" },
  { method: "GET", route: "/api/exchange/market/buyback/log", description: "Stored Buyback Sweep Log batches (purchased and skipped listings with reasons). Batches older than 5 days are omitted; the scheduler deletes them from disk at most hourly." },
  { method: "POST", route: "/api/exchange/market/buyback/log", description: "Read-only dry-run classify of player sell listings (eligible first, then skip reasons; capped at 1000 stored rows with leftovers reserved); appends a log batch (no backup taken). Rate-limited." },
  { method: "POST", route: "/api/exchange/market/buyback/log/clear", description: "Clear stored Buyback Sweep Log batches. Requires `exchange:market-write`. Rate-limited." },
  { method: "POST", route: "/api/exchange/market/buyback/schedule", description: "Save the buyback schedule (audited, rate-limited)" },
  { method: "POST", route: "/api/exchange/market/seed/schedule", description: "Save the market reseed schedule (audited, rate-limited)" },
  { method: "POST", route: "/api/exchange/market/buyback/run", description: "Run a buyback sweep now with the saved schedule (probe → backup → sweep)" },
  { method: "POST", route: "/api/exchange/market/seed/run", description: "Run a market reseed now with the saved schedule (backup → clear bot listings → seed)" },
  { method: "POST", route: "/api/exchange/market/seed/clear", description: "Remove the bot's NPC listings from one exchange without reseeding (probe → backup → clear; no backup when the bot has none). Player listings and pending seller payments are never touched. Requires `exchange:market-write`. Rate-limited." },
  { method: "GET", route: "/api/exchange/market/plans/csv", description: "Download the selected (or active) seed plan as CSV" },
  { method: "POST", route: "/api/exchange/market/plans/csv", description: "Upload a UTF-8 CSV as the current seeding list: creates or replaces a named custom plan and makes it active. Only the documented seed-plan columns (names and numbers) are accepted; extra columns, SQL/JSON/HTML, formulas, and non-numeric cells are rejected. The bundled plan is never overwritten. Requires `exchange:market-write`. Rate-limited." },
  { method: "POST", route: "/api/exchange/market/plans/active", description: "Set the active seed plan used by reseed and buyback" },
  { method: "POST", route: "/api/exchange/market/plans/name", description: "Rename a custom seed plan" },
  { method: "GET", route: "/api/exchange/market/items", description: "Merged, display-ready bot item catalog (bundled plan rows + admin-added new items), annotated with `overridden`/`isNew`/`unsafe` per row" },
  { method: "GET", route: "/api/exchange/market/items/catalog", description: "Item picker for \"add item\": `admin-items.json` filtered to allowed categories and unsafe-id-free" },
  { method: "POST", route: "/api/exchange/market/items", description: "Save per-item overrides/new items/removals in one batch (audited, rate-limited). Requires `exchange:market-write`." },
  { method: "GET", route: "/api/blueprints", description: "List all blueprints" },
  { method: "GET", route: "/api/blueprints/{blueprintId}/export", description: "Export single blueprint" },
  { method: "POST", route: "/api/blueprints/export", description: "Bulk export blueprints" },
  { method: "POST", route: "/api/blueprints/import", description: "Import blueprint file" },
  { method: "DELETE", route: "/api/blueprints/{blueprintId}", description: "Delete blueprint" },
  { method: "GET", route: "/api/maps", description: "List all maps" },
  { method: "GET", route: "/api/map/status", description: "Get status of all maps" },
  { method: "GET", route: "/api/maps/mode", description: "Get map mode (static/dynamic)" },
  { method: "POST", route: "/api/maps/mode", description: "Set map mode" },
  { method: "POST", route: "/api/maps/settings", description: "Save map settings" },
  { method: "GET", route: "/api/maps/runtime-settings", description: "Get runtime configuration" },
  { method: "POST", route: "/api/maps/runtime-settings", description: "Save runtime configuration" },
  { method: "POST", route: "/api/maps/reconcile", description: "Reconcile map state" },
  { method: "POST", route: "/api/maps/spawn", description: "Spawn map server" },
  { method: "POST", route: "/api/maps/despawn", description: "Despawn map server" },
  { method: "POST", route: "/api/maps/respawn", description: "Restart a map with no managed service (despawn then respawn its partition)" },
  { method: "GET", route: "/api/maps/memory", description: "Get memory status" },
  { method: "POST", route: "/api/maps/memory", description: "Set/unset map memory" },
  { method: "GET", route: "/api/maps/memory/balancer", description: "Get memory balancer state" },
  { method: "POST", route: "/api/maps/memory/balancer", description: "Enable/disable memory balancer" },
  { method: "GET", route: "/api/maps/memory/swap", description: "Get memory swap status" },
  { method: "POST", route: "/api/maps/memory/swap", description: "Enable/disable memory swap" },
  { method: "GET", route: "/api/maps/memory/live", description: "Get live per-map RAM usage and, when enabled/supported, current swap usage and allowance" },
  { method: "GET", route: "/api/maps/autoscaler", description: "Get autoscaler status" },
  { method: "POST", route: "/api/maps/autoscaler", description: "Autoscaler action" },
  { method: "GET", route: "/api/maps/spicefields", description: "List spicefields" },
  { method: "PATCH", route: "/api/maps/spicefields/{typeId}", description: "Update spicefield config" },
  { method: "GET", route: "/api/maps/choam-terminals", description: "Get CHOAM terminal overview" },
  { method: "POST", route: "/api/maps/choam-terminals", description: "Install CHOAM terminals" },
  { method: "DELETE", route: "/api/maps/choam-terminals", description: "Remove CHOAM terminals" },
  { method: "GET", route: "/api/maps/combat-state", description: "Get combat state by partition" },
  { method: "GET", route: "/api/maps/user-settings/schema", description: "Get user settings schema" },
  { method: "GET", route: "/api/maps/user-settings/restart-pending", description: "Check if a Landsraad-field restart is pending" },
  { method: "GET", route: "/api/maps/user-settings/deferred-pending", description: "Check if a \"Restart later\" deferred save is pending (any UserEngine/UserGame save)" },
  { method: "GET", route: "/api/maps/user-settings/values", description: "Get settings values" },
  { method: "GET", route: "/api/maps/user-settings/raw", description: "Get raw settings file" },
  { method: "POST", route: "/api/maps/user-settings/save", description: "Save user settings" },
  { method: "POST", route: "/api/maps/user-settings/reset", description: "Reset to defaults" },
  { method: "POST", route: "/api/maps/user-settings/raw", description: "Save raw settings" },
  { method: "POST", route: "/api/maps/user-settings/materialize", description: "Refresh settings" },
  { method: "GET", route: "/api/maps/userengine", description: "Get UserEngine configuration" },
  { method: "GET", route: "/api/maps/usergame", description: "Get UserGame configuration" },
  { method: "GET", route: "/api/sietches", description: "List sietches" },
  { method: "GET", route: "/api/sietches/dimensions", description: "Get sietch dimensions" },
  { method: "POST", route: "/api/sietches/update", description: "Update sietch config" },
  { method: "GET", route: "/api/deepdesert", description: "Get Deep Desert status" },
  { method: "POST", route: "/api/deepdesert/update", description: "Update Deep Desert" },
  { method: "GET", route: "/api/map/capabilities", description: "Get map feature capabilities" },
  { method: "GET", route: "/api/map/markers", description: "Get map markers & configuration (actors, merged with spice/POI rows; response also includes `coriolisSeed`, `coriolisNextCycleAt`, `coriolisSeedStaleSince`, and `coriolisLayout`)" },
  { method: "GET", route: "/api/map/spice", description: "Get spice/flour-sand layers (static pool, active blows, flour sand) for a map/partition" },
  { method: "GET", route: "/api/map/poi", description: "Get registry-driven POI layers (ore, scrap, flora, poi, house_representative, trainer, fortress, hazard, enemy) for a map" },
  { method: "POST", route: "/api/map/teleport-player", description: "Teleport a player to coordinates in the player's current ready partition; this never starts a dynamic map or crosses partitions" },
  { method: "GET", route: "/api/map/partitions", description: "List live-map partitions, including `alive` and `ready` runtime state for stopped dynamic maps" },
  { method: "GET", route: "/api/map/players", description: "Get player positions" },
  { method: "GET", route: "/api/map/bases", description: "Get base locations" },
  { method: "GET", route: "/api/map/storage", description: "Get storage locations" },
  { method: "GET", route: "/api/map/services", description: "Get service locations" },
  { method: "GET", route: "/api/database/status", description: "Database status" },
  { method: "GET", route: "/api/database/schemas", description: "List database schemas" },
  { method: "GET", route: "/api/database/tables", description: "List tables in schema" },
  { method: "GET", route: "/api/database/tables/{schema}/{table}/columns", description: "Get column information" },
  { method: "GET", route: "/api/database/tables/{schema}/{table}/preview", description: "Preview table data" },
  { method: "GET", route: "/api/database/tables/{schema}/{table}/count", description: "Get row count" },
  { method: "PATCH", route: "/api/database/tables/{schema}/{table}/row", description: "Update table row" },
  { method: "GET", route: "/api/database/search", description: "Search database" },
  { method: "POST", route: "/api/database/query", description: "Execute SQL query" },
  { method: "POST", route: "/api/database/export", description: "Export query results" },
  { method: "POST", route: "/api/database/password", description: "Change database password" },
  { method: "GET", route: "/api/database/table/{table}", description: "Preview table" },
  { method: "GET", route: "/api/admin/items/catalog", description: "Item catalog with search" },
  { method: "GET", route: "/api/admin/items/search", description: "Search items" },
  { method: "GET", route: "/api/admin/items", description: "List items by category" },
  { method: "GET", route: "/api/admin/vehicles/structured", description: "Get structured vehicle list" },
  { method: "GET", route: "/api/admin/vehicles", description: "List or search vehicles" },
  { method: "GET", route: "/api/admin/skill-modules", description: "List or search skill modules" },
  { method: "GET", route: "/api/admin/history", description: "Get admin command history" },
  { method: "POST", route: "/api/admin/history/clear", description: "Clear admin history" },
  { method: "GET", route: "/api/admin/character-transfer-settings", description: "Get character transfer settings" },
  { method: "POST", route: "/api/admin/character-transfer-settings", description: "Save/restore character transfer settings" },
  { method: "GET", route: "/api/admin/message-of-the-day", description: "Get MOTD settings" },
  { method: "POST", route: "/api/admin/message-of-the-day", description: "Save/restore MOTD" },
  { method: "GET", route: "/api/admin/player-announcements", description: "Get announcement settings" },
  { method: "POST", route: "/api/admin/player-announcements", description: "Save/restore announcements" },
  { method: "GET", route: "/api/admin/landsraad", description: "Get Landsraad overview" },
  { method: "GET", route: "/api/admin/landsraad/milestone-preset", description: "Get milestone preset" },
  { method: "POST", route: "/api/admin/landsraad/milestone-preset", description: "Save milestone preset" },
  { method: "POST", route: "/api/admin/landsraad/task-goal", description: "Update task goal" },
  { method: "POST", route: "/api/admin/landsraad/term-task-goals", description: "Update term task goals" },
  { method: "POST", route: "/api/admin/landsraad/reward-tier", description: "Update reward tier" },
  { method: "POST", route: "/api/admin/landsraad/player-contribution", description: "Set player contribution" },
  { method: "POST", route: "/api/admin/broadcast", description: "Broadcast message to all" },
  { method: "POST", route: "/api/admin/map-chat", description: "Send map chat message" },
  { method: "POST", route: "/api/admin/broadcast-shutdown", description: "Broadcast shutdown notice" },
  { method: "GET", route: "/api/care-package/capabilities", description: "Get care package capabilities" },
  { method: "GET", route: "/api/care-package/config", description: "Get care package configuration" },
  { method: "POST", route: "/api/care-package/config", description: "Save care package config" },
  { method: "GET", route: "/api/care-package/grants", description: "Get grant history" },
  { method: "GET", route: "/api/care-package/history", description: "Get grant history (alias)" },
  { method: "POST", route: "/api/care-package/history/clear", description: "Clear grant history" },
  { method: "GET", route: "/api/care-package/eligible", description: "Get eligible players" },
  { method: "POST", route: "/api/care-package/grant-eligible", description: "Grant to eligible players" },
  { method: "POST", route: "/api/care-package/run", description: "Run care package scan" },
  { method: "POST", route: "/api/care-package/grant/{playerId}", description: "Grant to specific player" },
  { method: "POST", route: "/api/care-package/retry/{grantId}", description: "Retry failed grant" },
  { method: "POST", route: "/api/care-package/enable", description: "Enable care package" },
  { method: "POST", route: "/api/care-package/disable", description: "Disable care package" },
  { method: "GET", route: "/api/addons/community", description: "Get community addon catalog" },
  { method: "GET", route: "/api/addons/installed", description: "Get installed addons" },
  { method: "POST", route: "/api/addons/community/install", description: "Install community addon" },
  { method: "POST", route: "/api/addons/community/update", description: "Update community addon" },
  { method: "POST", route: "/api/addons/installed/{id}/enable", description: "Enable addon" },
  { method: "POST", route: "/api/addons/installed/{id}/disable", description: "Disable addon" },
  { method: "DELETE", route: "/api/addons/installed/{id}", description: "Remove addon" },
  { method: "POST", route: "/api/addons/installed/{id}/bridge", description: "Addon bridge API" },
  { method: "GET", route: "/api/addons/installed/{id}/content/{path}", description: "Get addon content file" },
  { method: "GET", route: "/api/logs/services", description: "List available services" },
  { method: "GET", route: "/api/logs/{service}", description: "Get service logs" },
  { method: "GET", route: "/api/logs/{service}/stream", description: "Stream service logs (SSE)" },
  { method: "GET", route: "/api/logs/{service}/download", description: "Download service logs" },
  { method: "POST", route: "/api/settings/admin-password", description: "Change admin password" },
  { method: "POST", route: "/api/settings/web-port", description: "Change web console port" },
  { method: "POST", route: "/api/settings", description: "Write config" },
  { method: "GET", route: "/api/settings", description: "Get setup state" },
  { method: "GET", route: "/api/public-directory/status", description: "Get public directory status" },
  { method: "POST", route: "/api/settings/public-directory", description: "Save public directory and anonymous-count settings" },
  { method: "POST", route: "/api/settings/public-directory/claim", description: "Claim server listing" },
  { method: "GET", route: "/api/settings/iam/policies", description: "Active policy store, plus `actions`: the full sorted catalog of valid action names" },
  { method: "PUT", route: "/api/settings/iam/policy", description: "Validate and atomically save the complete policy store" },
  { method: "POST", route: "/api/settings/iam/policy/test", description: "Evaluate one action for one tier without changing policy" },
  { method: "GET", route: "/api/settings/api-keys", description: "List API keys, without any secret or hash" },
  { method: "GET", route: "/api/settings/api-keys/catalog", description: "List the namespaces a key can be scoped to, and whether each supports writes" },
  { method: "POST", route: "/api/settings/api-keys", description: "Create a key. Returns the full key once, in `secret`" },
  { method: "PUT", route: "/api/settings/api-keys/{id}", description: "Update a key. `scopes` replaces wholesale" },
  { method: "DELETE", route: "/api/settings/api-keys/{id}", description: "Revoke a key permanently" },
  { method: "GET", route: "/api/integrations/discord/health", description: "Adapter health status" },
  { method: "GET", route: "/api/integrations/discord/status", description: "Server status" },
  { method: "GET", route: "/api/integrations/discord/readiness", description: "Service readiness" },
  { method: "GET", route: "/api/integrations/discord/services", description: "Services list" },
  { method: "GET", route: "/api/integrations/discord/population", description: "Player population" },
  { method: "GET", route: "/api/integrations/discord/version", description: "Adapter version" },
  { method: "GET", route: "/api/integrations/discord/servers", description: "Servers list" },
  { method: "GET", route: "/api/integrations/discord/ports", description: "Ports list" },
  { method: "GET", route: "/api/integrations/discord/catalog", description: "Command catalog (names/descriptions/capabilities/min tiers for every live route below, machine-readable)" },
  { method: "GET", route: "/api/integrations/discord/logs", description: "Service logs" },
  { method: "GET", route: "/api/integrations/discord/ops/activity", description: "Ops activity" },
  { method: "GET", route: "/api/integrations/discord/ops/combat", description: "Ops combat stats" },
  { method: "GET", route: "/api/integrations/discord/ops/resources", description: "Ops resources" },
  { method: "GET", route: "/api/integrations/discord/ops/economy", description: "Ops economy" },
  { method: "GET", route: "/api/integrations/discord/map-state", description: "Map state" },
  { method: "POST", route: "/api/integrations/discord/maintenance", description: "Maintenance mode" },
  { method: "GET", route: "/api/integrations/discord/backups/list", description: "Backup list" },
  { method: "POST", route: "/api/integrations/discord/broadcast", description: "Send broadcast" },
  { method: "POST", route: "/api/integrations/discord/announcements", description: "Send announcements" },
  { method: "POST", route: "/api/integrations/discord/players/link", description: "Link Discord to player" },
  { method: "POST", route: "/api/integrations/discord/players/link/verify", description: "Verify player link" },
  { method: "POST", route: "/api/integrations/discord/players/unlink", description: "Unlink Discord from player" },
  { method: "GET", route: "/api/integrations/discord/players/me", description: "Get current player" },
  { method: "GET", route: "/api/integrations/discord/players/inventory", description: "Get player inventory" },
  { method: "GET", route: "/api/integrations/discord/players/storage", description: "Get player storage" },
  { method: "GET", route: "/api/integrations/discord/players/find", description: "Find player" },
  { method: "GET", route: "/api/integrations/discord/players/inventory-search", description: "Search inventory" },
  { method: "GET", route: "/api/integrations/discord/guilds/storage", description: "Get guild storage" },
  { method: "GET", route: "/api/integrations/discord/guilds/find", description: "Find guild" },
  { method: "POST", route: "/api/integrations/discord/db", description: "Database query (planned)" },
] satisfies EndpointDefinition[]);

function loadEndpointCatalog(): EndpointDefinition[] {
  return ENDPOINT_CATALOG.map((endpoint) => ({ ...endpoint }));
}

function resolveRoute(route: string, parameters: RouteParameters = {}): string {
  return route.replace(/\{([^}]+)\}/g, (_, parameterName: string): string => {
    const value = parameters[parameterName];

    if (value === undefined || value === null) {
      throw new Error(`Missing route parameter: ${parameterName}`);
    }

    return encodeURIComponent(String(value));
  });
}

export { ENDPOINT_CATALOG, loadEndpointCatalog, resolveRoute };

export type { EndpointDefinition, HttpMethod, RouteParameters };
